# -*-coding:utf-8-*-
__author__ = 'csy'

from Page import conf, testcase
from model import executer
import os, inspect
from datetime import datetime, date
import random


def Case30():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1662)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1663)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1664)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1666)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1667)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1669)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1670)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1671)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1674)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1675)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1676)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1677)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1678)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1679)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1681)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1682)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1685)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1687)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1688)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1691)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1692)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1693)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1696)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1697)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1699)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1703)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1714)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1716)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1720)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1721)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1722)

def Case1():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1723)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_3)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_5)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_7)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_8)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_9)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_10)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_11)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_12)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_15)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_16)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_17)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_18)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_19)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_20)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_21)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_23)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_24)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_26)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_27)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_28)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_29)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_30)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_31)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_32)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_47)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_49)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_50)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_52)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_57)

def Case2():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_58)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_59)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_63)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_64)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_65)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_66)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_67)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_68)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_69)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_73)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_75)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_76)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_79)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_82)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_83)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_98)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_100)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_102)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_104)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_106)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_107)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_109)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_110)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_112)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_116)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_118)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_119)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_131)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_134)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_135)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_136)

def Case3():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_138)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_139)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_141)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_142)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_143)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_145)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_147)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_150)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1066)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1068)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1084)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1085)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1088)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1089)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1090)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1094)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1095)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1096)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1347)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1323)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1304)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1307)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1308)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1312)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1314)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1315)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_164)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_166)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_167)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_170)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_171)

def Case4():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_173)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_178)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_179)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_180)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_181)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_185)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_186)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_188)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_193)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_194)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_198)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_199)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_201)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_202)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_203)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_204)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_207)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_209)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_210)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_211)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_212)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_214)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_215)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_217)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_218)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_235)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_236)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_237)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_238)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_239)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_240)

def Case5():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_248)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_250)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_252)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_253)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_255)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_258)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_260)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_261)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_262)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_270)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_271)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_274)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_276)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_279)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_280)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_281)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_285)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_290)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_291)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_293)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_295)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_296)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_297)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_309)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_310)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_312)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_315)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_316)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_319)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_320)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_325)

def Case6():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_326)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_327)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_330)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_332)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_333)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_334)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_339)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_341)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_342)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_347)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_348)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_349)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_352)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_353)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_354)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_355)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_356)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_357)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_361)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_362)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_363)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_366)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_370)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_372)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_373)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_375)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_376)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_378)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_379)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_380)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_384)

def Case7():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_386)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_395)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_402)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1444)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1445)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1446)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1447)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1448)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1449)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_274)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_276)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_279)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_309)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_310)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_312)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_315)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1364)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1365)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1367)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1377)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1379)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_403)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_413)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_414)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_417)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_419)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_420)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_421)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_422)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_423)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_425)

def Case8():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_430)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_431)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_434)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_436)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_438)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_439)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_444)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_445)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_447)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_448)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_449)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_451)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_452)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_454)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_455)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_457)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_459)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_460)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_461)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_462)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_463)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_469)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_471)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_474)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_475)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_476)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_480)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_482)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_483)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_485)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_489)

def Case9():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_491)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_492)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_493)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_496)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_497)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_506)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_507)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_510)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_511)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_512)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_514)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_515)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_517)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_526)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_527)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_531)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_532)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_537)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_538)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_539)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_540)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_541)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_547)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_548)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_551)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_560)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_561)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_566)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_568)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_569)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_571)

def Case10():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_572)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_573)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_575)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_583)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_585)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_591)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_592)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_594)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_596)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_598)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_599)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_600)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_601)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_602)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_603)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_605)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_613)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_614)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_615)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_616)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_618)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_622)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_623)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_624)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_629)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_635)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_636)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_657)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_662)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1391)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1405)

def Case11():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1420)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_9)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_10)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_11)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_12)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_15)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_16)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_17)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_18)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_19)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_20)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_21)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_23)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_24)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_26)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_27)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_700)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_702)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_704)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_707)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_708)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_715)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_726)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_727)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_728)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_729)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_975)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_979)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_980)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_981)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_982)

def Case12():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_983)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_984)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_985)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_986)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_987)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_988)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_993)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_995)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_996)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_997)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_999)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1000)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1009)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1010)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1011)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1012)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1013)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1014)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1015)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1016)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1023)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1024)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1025)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1027)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1031)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1032)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1033)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1036)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1037)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1038)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1040)

def Case13():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1041)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1042)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1052)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1055)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1056)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1057)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1062)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1065)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1066)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1068)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1084)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1085)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1088)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1089)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1090)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1094)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1095)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1096)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1097)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1100)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1789)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1109)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1111)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1112)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1120)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1124)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1137)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1141)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1142)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1143)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1152)

def Case14():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1154)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1157)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1158)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1160)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1161)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1162)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1163)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1164)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1166)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1169)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1172)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1173)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1174)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1180)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1181)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1184)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1186)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1193)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1196)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1198)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1199)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1204)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1211)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1212)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_28)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_29)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_30)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_31)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_32)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_47)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1530)

def Case15():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1518)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1193)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1196)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1198)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1199)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1204)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_840)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_841)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_843)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_848)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_853)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1213)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1214)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1225)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1229)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1237)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1238)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1248)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1250)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1251)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1252)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_738)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_739)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_740)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_743)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_748)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_752)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_753)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_757)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_764)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_766)

def Case16():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_767)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_768)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_769)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_770)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_773)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_775)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_776)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_782)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_783)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_785)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_786)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_787)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_788)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_789)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_790)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_791)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_793)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_794)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_795)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_796)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_797)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_799)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_800)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_807)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_815)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_816)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_817)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_819)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_820)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_821)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_822)

def Case17():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_824)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_827)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_831)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_832)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_833)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_835)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_836)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_840)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_841)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_843)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_848)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_853)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_854)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_855)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_859)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_861)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_862)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_865)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_866)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_868)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_869)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_870)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_872)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_873)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_876)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_877)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_878)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_882)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_885)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_886)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_887)

def Case18():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_889)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_891)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_892)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_898)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_899)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_902)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_911)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_912)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_913)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_919)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_920)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_921)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_922)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_923)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_926)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_929)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_930)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_931)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_932)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_854)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_855)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_859)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_861)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_862)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_865)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_866)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_868)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_869)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_870)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_872)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1662)

def Case19():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1704)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1705)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_131)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_134)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_135)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_136)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_935)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_944)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_954)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_957)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_958)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_971)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_972)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_973)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1276)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1279)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1281)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1282)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1284)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1285)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1286)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1290)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1296)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1304)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1307)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1308)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1312)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1314)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1315)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1319)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1320)

def Case20():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1323)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1330)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1331)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1333)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1334)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1336)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1337)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1346)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1347)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1349)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1351)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1352)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1353)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1354)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1355)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1364)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1365)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1367)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1377)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1379)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1384)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1385)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1386)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1387)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1391)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1405)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1406)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1420)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1429)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1430)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1438)

def Case21():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1441)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1442)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1443)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1444)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1445)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1446)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1447)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1448)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1449)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1450)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1452)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1453)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1454)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1456)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1457)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1458)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1461)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1462)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1467)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1468)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1472)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1473)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1475)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1478)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1479)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1480)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1482)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1483)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1485)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1487)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1489)

def Case22():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1490)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1491)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1493)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1494)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1496)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1498)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1499)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1501)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1008)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1502)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1506)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1508)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1509)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1510)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1511)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1512)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1514)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1515)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1517)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1518)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1519)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1521)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1522)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1524)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1525)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1526)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1527)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1528)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1529)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1530)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1532)

def Case23():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1533)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1732)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_664)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_665)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_666)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_668)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_672)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_673)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_683)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_685)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_686)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_690)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_691)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_694)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_697)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_698)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_699)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1534)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1536)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1537)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1540)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1541)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1543)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1544)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1545)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1546)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1547)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1549)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1550)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1552)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1553)

def Case24():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1556)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1558)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1560)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1561)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1562)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1563)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1564)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1565)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1567)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1569)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1573)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1574)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1576)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1577)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1578)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1579)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1580)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1581)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1583)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1584)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1586)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1587)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1588)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1590)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1591)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1592)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1593)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1594)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1595)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1599)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1600)

def Case25():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1601)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1606)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1607)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1608)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1609)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1610)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1612)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1613)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1614)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1615)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1616)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1617)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1620)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1621)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1623)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1624)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1625)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1626)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1627)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1628)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1629)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1630)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_138)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_188)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_193)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_194)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_198)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_199)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_201)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_202)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_203)

def Case26():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_204)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_207)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_209)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_248)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_250)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_252)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_253)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_255)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_258)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1631)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1632)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1633)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1634)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1635)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_959)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_955)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1636)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1637)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1638)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1641)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1642)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1643)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1644)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1646)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1654)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1655)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1656)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1657)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1658)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1659)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1660)

def Case27():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1799)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1885)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1349)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1351)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1352)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1353)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1354)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1355)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1406)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1430)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_261)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_262)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_270)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_271)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_235)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_236)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_237)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_238)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_239)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_240)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_248)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_250)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_690)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_691)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1214)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1384)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1385)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1386)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1387)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1529)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1732)

def Case28():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1461)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1462)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1008)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_783)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_782)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_785)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1319)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_280)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_281)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_285)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_290)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_291)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_293)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_295)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_296)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_297)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1881)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1689)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_980)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_981)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_982)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_983)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_984)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_985)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_986)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_987)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_63)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_64)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_65)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_66)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1010)

def Case29():
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1011)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1012)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1013)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1014)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1015)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1016)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_75)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_76)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_79)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_82)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_83)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_98)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1055)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1056)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1057)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1062)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1065)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_260)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1450)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1452)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1453)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1454)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1456)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1457)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1458)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1467)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_1468)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_316)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_319)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_320)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_325)
    executer.run(conf.Brush, testcase.brandvalidations.TestCase_326)


if __name__ == "__main__":
    dayOfWeek = datetime.now().weekday()
    print dayOfWeek

    # dayOfWeek = datetime.today().weekday()
    # print dayOfWeek
    try:
        # RESULT_PATH = os.path.dirname(os.path.abspath(inspect.stack()[-1][1]))
        # path = RESULT_PATH.split('/')[3]

        if dayOfWeek == 0:
            i = random.randint(1, 4)
            if i == 1:
                Case1()
            elif i == 2:
                Case2()
            elif i == 3:
                Case3()
            else:
                Case4()
        elif dayOfWeek == 1:
            i = random.randint(4, 7)
            if i == 4:
                Case5()
            elif i == 5:
                Case6()
            elif i == 6:
                Case7()
            else:
                Case8()
        elif dayOfWeek == 2:
            i = random.randint(7, 10)
            if i == 7:
                Case9()
            elif i == 8:
                Case10()
            elif i == 9:
                Case11()
            else:
                Case12()
        elif dayOfWeek == 3:
            i = random.randint(10, 13)
            if i == 10:
                Case13()
            elif i == 11:
                Case14()
            elif i == 12:
                Case15()
            else:
                Case16()
        elif dayOfWeek == 4:
            i = random.randint(13, 16)
            if i == 13:
                Case17()
            elif i == 14:
                Case18()
            elif i == 15:
                Case19()
            else:
                Case20()
        elif dayOfWeek ==5:
            i = random.randint(16, 19)
            if i == 16:
                Case21()
            elif i == 17:
                Case22()
            elif i == 18:
                Case23()
            else:
                Case24()
        elif dayOfWeek ==6:
            i = random.randint(19, 24)
            if i == 19:
                Case25()
            elif i == 20:
                Case26()
            elif i == 21:
                Case27()
            elif i == 22:
                Case28()
            elif i == 23:
                Case29()
            else:
                Case30()
    except IndexError:
        Case1()
