# -*- coding: utf-8 -*-
from Page import conf, testcase
from model import executer,env


def Case1():
	executer.run(conf.Brush, testcase.validations.TestCase_1)
	executer.run(conf.Brush, testcase.validations.TestCase_2)
	executer.run(conf.Brush, testcase.validations.TestCase_3)
	executer.run(conf.Brush, testcase.validations.TestCase_4)
	executer.run(conf.Brush, testcase.validations.TestCase_5)
	executer.run(conf.Brush, testcase.validations.TestCase_6)
	executer.run(conf.Brush, testcase.validations.TestCase_7)
	executer.run(conf.Brush, testcase.validations.TestCase_8)
	executer.run(conf.Brush, testcase.validations.TestCase_9)
	executer.run(conf.Brush, testcase.validations.TestCase_10)
	executer.run(conf.Brush, testcase.validations.TestCase_11)
	executer.run(conf.Brush, testcase.validations.TestCase_12)
	executer.run(conf.Brush, testcase.validations.TestCase_13)
	executer.run(conf.Brush, testcase.validations.TestCase_14)
	executer.run(conf.Brush, testcase.validations.TestCase_15)
	executer.run(conf.Brush, testcase.validations.TestCase_16)
	executer.run(conf.Brush, testcase.validations.TestCase_17)
	executer.run(conf.Brush, testcase.validations.TestCase_18)
	executer.run(conf.Brush, testcase.validations.TestCase_19)
	executer.run(conf.Brush, testcase.validations.TestCase_20)
	executer.run(conf.Brush, testcase.validations.TestCase_21)
	executer.run(conf.Brush, testcase.validations.TestCase_22)
	executer.run(conf.Brush, testcase.validations.TestCase_23)
	executer.run(conf.Brush, testcase.validations.TestCase_24)
	executer.run(conf.Brush, testcase.validations.TestCase_25)
	executer.run(conf.Brush, testcase.validations.TestCase_26)
	executer.run(conf.Brush, testcase.validations.TestCase_27)
	executer.run(conf.Brush, testcase.validations.TestCase_28)
	executer.run(conf.Brush, testcase.validations.TestCase_29)
	executer.run(conf.Brush, testcase.validations.TestCase_30)
	executer.run(conf.Brush, testcase.validations.TestCase_31)
	executer.run(conf.Brush, testcase.validations.TestCase_32)
	executer.run(conf.Brush, testcase.validations.TestCase_33)
	executer.run(conf.Brush, testcase.validations.TestCase_34)
	executer.run(conf.Brush, testcase.validations.TestCase_35)
	executer.run(conf.Brush, testcase.validations.TestCase_36)
	executer.run(conf.Brush, testcase.validations.TestCase_37)
	executer.run(conf.Brush, testcase.validations.TestCase_38)
	executer.run(conf.Brush, testcase.validations.TestCase_39)
	executer.run(conf.Brush, testcase.validations.TestCase_40)
	executer.run(conf.Brush, testcase.validations.TestCase_41)
	executer.run(conf.Brush, testcase.validations.TestCase_42)
	executer.run(conf.Brush, testcase.validations.TestCase_43)
	executer.run(conf.Brush, testcase.validations.TestCase_44)
	executer.run(conf.Brush, testcase.validations.TestCase_45)
	executer.run(conf.Brush, testcase.validations.TestCase_46)
	executer.run(conf.Brush, testcase.validations.TestCase_47)
	executer.run(conf.Brush, testcase.validations.TestCase_48)
	executer.run(conf.Brush, testcase.validations.TestCase_49)

if __name__ == "__main__":
	Case1()